import platform
from distutils.core import setup, Extension
from Cython.Build import cythonize

if platform.system() != 'Darwin':
    extra_compile_args = ['-O3']
    extra_link_args = []

else:
    extra_compile_args = ['-g3', '-O0', '-stdlib=libc++']
    extra_link_args = ['-stdlib=libc++']


extra_compile_args.extend(['-std=c++17'])

glew = ('glew', {'sources': ["src/extern/glew/src/glew.c"], 'include_dirs': ["src/extern/glew/include/"]})


setup(
    name='WoW Blender Studio Kernel',
    ext_modules=cythonize([Extension(
        "wbs_kernel",
        sources=[
            "src/wbs_kernel.pyx",
            "src/render/m2_drawing_batch.cpp",
            "src/render/m2_drawing_mesh.cpp",
            "src/render/opengl_utils.cpp"
        ],

        include_dirs=[
            "src/",
            "src/render/",
            "src/bpy_boost/src/",
            "src/extern/glew/include/GL/",
            "src/extern/glm/",
            "src/extern/",
            "src/bl_src",
            "src/bl_src/source",
            "src/bl_src/source/blender",
            "src/bl_src/source/blender/blenloader",
            "src/bl_src/source/blender/blenloader/intern",
            "src/bl_src/source/blender/blentranslation",
            "src/bl_src/source/blender/blentranslation/intern",
            "src/bl_src/source/blender/blentranslation/msgfmt",
            "src/bl_src/source/blender/depsgraph",
            "src/bl_src/source/blender/depsgraph/intern",
            "src/bl_src/source/blender/depsgraph/intern/eval",
            "src/bl_src/source/blender/depsgraph/intern/node",
            "src/bl_src/source/blender/depsgraph/intern/builder",
            "src/bl_src/source/blender/depsgraph/intern/debug",
            "src/bl_src/source/blender/modifiers",
            "src/bl_src/source/blender/modifiers/intern",
            "src/bl_src/source/blender/gpu",
            "src/bl_src/source/blender/gpu/shaders",
            "src/bl_src/source/blender/gpu/shaders/material",
            "src/bl_src/source/blender/gpu/intern",
            "src/bl_src/source/blender/python",
            "src/bl_src/source/blender/python/gpu",
            "src/bl_src/source/blender/python/bmesh",
            "src/bl_src/source/blender/python/mathutils",
            "src/bl_src/source/blender/python/generic",
            "src/bl_src/source/blender/python/intern",
            "src/bl_src/source/blender/windowmanager",
            "src/bl_src/source/blender/windowmanager/message_bus",
            "src/bl_src/source/blender/windowmanager/message_bus/intern",
            "src/bl_src/source/blender/windowmanager/gizmo",
            "src/bl_src/source/blender/windowmanager/gizmo/intern",
            "src/bl_src/source/blender/windowmanager/xr",
            "src/bl_src/source/blender/windowmanager/xr/intern",
            "src/bl_src/source/blender/windowmanager/intern",
            "src/bl_src/source/blender/nodes",
            "src/bl_src/source/blender/nodes/composite",
            "src/bl_src/source/blender/nodes/composite/nodes",
            "src/bl_src/source/blender/nodes/texture",
            "src/bl_src/source/blender/nodes/texture/nodes",
            "src/bl_src/source/blender/nodes/shader",
            "src/bl_src/source/blender/nodes/shader/nodes",
            "src/bl_src/source/blender/nodes/intern",
            "src/bl_src/source/blender/compositor",
            "src/bl_src/source/blender/compositor/nodes",
            "src/bl_src/source/blender/compositor/operations",
            "src/bl_src/source/blender/compositor/intern",
            "src/bl_src/source/blender/editors",
            "src/bl_src/source/blender/editors/mesh",
            "src/bl_src/source/blender/editors/space_api",
            "src/bl_src/source/blender/editors/interface",
            "src/bl_src/source/blender/editors/space_console",
            "src/bl_src/source/blender/editors/space_node",
            "src/bl_src/source/blender/editors/space_topbar",
            "src/bl_src/source/blender/editors/sculpt_paint",
            "src/bl_src/source/blender/editors/armature",
            "src/bl_src/source/blender/editors/util",
            "src/bl_src/source/blender/editors/space_text",
            "src/bl_src/source/blender/editors/space_graph",
            "src/bl_src/source/blender/editors/include",
            "src/bl_src/source/blender/editors/io",
            "src/bl_src/source/blender/editors/curve",
            "src/bl_src/source/blender/editors/render",
            "src/bl_src/source/blender/editors/animation",
            "src/bl_src/source/blender/editors/gpencil",
            "src/bl_src/source/blender/editors/space_image",
            "src/bl_src/source/blender/editors/space_sequencer",
            "src/bl_src/source/blender/editors/gizmo_library",
            "src/bl_src/source/blender/editors/gizmo_library/gizmo_types",
            "src/bl_src/source/blender/editors/gizmo_library/geometry",
            "src/bl_src/source/blender/editors/undo",
            "src/bl_src/source/blender/editors/space_action",
            "src/bl_src/source/blender/editors/space_info",
            "src/bl_src/source/blender/editors/lattice",
            "src/bl_src/source/blender/editors/metaball",
            "src/bl_src/source/blender/editors/mask",
            "src/bl_src/source/blender/editors/space_statusbar",
            "src/bl_src/source/blender/editors/space_script",
            "src/bl_src/source/blender/editors/object",
            "src/bl_src/source/blender/editors/space_nla",
            "src/bl_src/source/blender/editors/screen",
            "src/bl_src/source/blender/editors/space_userpref",
            "src/bl_src/source/blender/editors/space_clip",
            "src/bl_src/source/blender/editors/space_view3d",
            "src/bl_src/source/blender/editors/datafiles",
            "src/bl_src/source/blender/editors/space_buttons",
            "src/bl_src/source/blender/editors/physics",
            "src/bl_src/source/blender/editors/space_file",
            "src/bl_src/source/blender/editors/uvedit",
            "src/bl_src/source/blender/editors/scene",
            "src/bl_src/source/blender/editors/space_outliner",
            "src/bl_src/source/blender/editors/sound",
            "src/bl_src/source/blender/editors/transform",
            "src/bl_src/source/blender/io",
            "src/bl_src/source/blender/io/avi",
            "src/bl_src/source/blender/io/avi/intern",
            "src/bl_src/source/blender/io/collada",
            "src/bl_src/source/blender/io/usd",
            "src/bl_src/source/blender/io/usd/intern",
            "src/bl_src/source/blender/io/alembic",
            "src/bl_src/source/blender/io/alembic/intern",
            "src/bl_src/source/blender/blenkernel",
            "src/bl_src/source/blender/blenkernel/intern",
            "src/bl_src/source/blender/blenlib",
            "src/bl_src/source/blender/blenlib/intern",
            "src/bl_src/source/blender/gpencil_modifiers",
            "src/bl_src/source/blender/gpencil_modifiers/intern",
            "src/bl_src/source/blender/render",
            "src/bl_src/source/blender/render/intern",
            "src/bl_src/source/blender/render/intern/include",
            "src/bl_src/source/blender/render/intern/source",
            "src/bl_src/source/blender/render/extern",
            "src/bl_src/source/blender/render/extern/include",
            "src/bl_src/source/blender/datatoc",
            "src/bl_src/source/blender/imbuf",
            "src/bl_src/source/blender/imbuf/intern",
            "src/bl_src/source/blender/imbuf/intern/openexr",
            "src/bl_src/source/blender/imbuf/intern/oiio",
            "src/bl_src/source/blender/imbuf/intern/cineon",
            "src/bl_src/source/blender/imbuf/intern/dds",
            "src/bl_src/source/blender/bmesh",
            "src/bl_src/source/blender/bmesh/tools",
            "src/bl_src/source/blender/bmesh/operators",
            "src/bl_src/source/blender/bmesh/intern",
            "src/bl_src/source/blender/ikplugin",
            "src/bl_src/source/blender/ikplugin/intern",
            "src/bl_src/source/blender/blenfont",
            "src/bl_src/source/blender/blenfont/intern",
            "src/bl_src/source/blender/makesdna",
            "src/bl_src/source/blender/makesdna/intern",
            "src/bl_src/source/blender/physics",
            "src/bl_src/source/blender/physics/intern",
            "src/bl_src/source/blender/shader_fx",
            "src/bl_src/source/blender/shader_fx/intern",
            "src/bl_src/source/blender/blendthumb",
            "src/bl_src/source/blender/blendthumb/src",
            "src/bl_src/source/blender/draw",
            "src/bl_src/source/blender/draw/engines",
            "src/bl_src/source/blender/draw/engines/eevee",
            "src/bl_src/source/blender/draw/engines/eevee/shaders",
            "src/bl_src/source/blender/draw/engines/basic",
            "src/bl_src/source/blender/draw/engines/basic/shaders",
            "src/bl_src/source/blender/draw/engines/gpencil",
            "src/bl_src/source/blender/draw/engines/gpencil/shaders",
            "src/bl_src/source/blender/draw/engines/workbench",
            "src/bl_src/source/blender/draw/engines/workbench/shaders",
            "src/bl_src/source/blender/draw/engines/external",
            "src/bl_src/source/blender/draw/engines/select",
            "src/bl_src/source/blender/draw/engines/select/shaders",
            "src/bl_src/source/blender/draw/engines/overlay",
            "src/bl_src/source/blender/draw/engines/overlay/shaders",
            "src/bl_src/source/blender/draw/intern",
            "src/bl_src/source/blender/draw/intern/shaders",
            "src/bl_src/source/blender/makesrna",
            "src/bl_src/source/blender/makesrna/rna_cleanup",
            "src/bl_src/source/blender/makesrna/intern",
            # "src/bl_src/source/blender/freestyle",
            # "src/bl_src/source/blender/freestyle/intern",
            # "src/bl_src/source/blender/freestyle/intern/blender_interface",
            # "src/bl_src/source/blender/freestyle/intern/python",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D/UnaryFunction1D_Vec3f",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D/UnaryFunction1D_double",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D/UnaryFunction1D_Vec2f",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D/UnaryFunction1D_Nature_EdgeNature",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D/UnaryFunction1D_vector_ViewShape",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D/UnaryFunction1D_void",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction1D/UnaryFunction1D_unsigned_int",
            # "src/bl_src/source/blender/freestyle/intern/python/BinaryPredicate1D",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryPredicate1D",
            # "src/bl_src/source/blender/freestyle/intern/python/Interface1D",
            # "src/bl_src/source/blender/freestyle/intern/python/Interface1D/Curve",
            # "src/bl_src/source/blender/freestyle/intern/python/Interface1D/FEdge",
            # "src/bl_src/source/blender/freestyle/intern/python/StrokeShader",
            # "src/bl_src/source/blender/freestyle/intern/python/Iterator",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryPredicate0D",
            # "src/bl_src/source/blender/freestyle/intern/python/Interface0D",
            # "src/bl_src/source/blender/freestyle/intern/python/Interface0D/CurvePoint",
            # "src/bl_src/source/blender/freestyle/intern/python/Interface0D/ViewVertex",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_ViewShape",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_unsigned_int",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_Vec2f",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_double",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_Nature_EdgeNature",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_Material",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_float",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_Id",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_vector_ViewShape",
            # "src/bl_src/source/blender/freestyle/intern/python/UnaryFunction0D/UnaryFunction0D_Vec3f",
            # "src/bl_src/source/blender/freestyle/intern/stroke",
            # "src/bl_src/source/blender/freestyle/intern/scene_graph",
            # "src/bl_src/source/blender/freestyle/intern/winged_edge",
            # "src/bl_src/source/blender/freestyle/intern/image",
            # "src/bl_src/source/blender/freestyle/intern/system",
            # "src/bl_src/source/blender/freestyle/intern/view_map",
            # "src/bl_src/source/blender/freestyle/intern/geometry",
            # "src/bl_src/source/blender/freestyle/intern/application",
            # "src/bl_src/tests",
            # "src/bl_src/tests/python",
            # "src/bl_src/tests/python/collada",
            # "src/bl_src/tests/python/collada/mesh",
            # "src/bl_src/tests/python/collada/animation",
            # "src/bl_src/tests/python/view_layer",
            # "src/bl_src/tests/python/modules",
            # "src/bl_src/release",
            # "src/bl_src/release/bin",
            # "src/bl_src/release/scripts",
            # "src/bl_src/release/scripts/templates_py",
            # "src/bl_src/release/scripts/addons_contrib",
            # "src/bl_src/release/scripts/addons",
            # "src/bl_src/release/scripts/templates_osl",
            # "src/bl_src/release/scripts/presets",
            # "src/bl_src/release/scripts/presets/cycles",
            # "src/bl_src/release/scripts/presets/cycles/integrator",
            # "src/bl_src/release/scripts/presets/cycles/sampling",
            # "src/bl_src/release/scripts/presets/tracking_track_color",
            # "src/bl_src/release/scripts/presets/ffmpeg",
            # "src/bl_src/release/scripts/presets/interface_theme",
            # "src/bl_src/release/scripts/presets/gpencil_material",
            # "src/bl_src/release/scripts/presets/tracking_camera",
            # "src/bl_src/release/scripts/presets/camera",
            # "src/bl_src/release/scripts/presets/render",
            # "src/bl_src/release/scripts/presets/fluid",
            # "src/bl_src/release/scripts/presets/tracking_settings",
            # "src/bl_src/release/scripts/presets/hair_dynamics",
            # "src/bl_src/release/scripts/presets/safe_areas",
            # "src/bl_src/release/scripts/presets/framerate",
            # "src/bl_src/release/scripts/presets/sss",
            # "src/bl_src/release/scripts/presets/cloth",
            # "src/bl_src/release/scripts/presets/keyconfig",
            # "src/bl_src/release/scripts/presets/keyconfig/keymap_data",
            # "src/bl_src/release/scripts/presets/operator",
            # "src/bl_src/release/scripts/presets/operator/wm.collada_export",
            # "src/bl_src/release/scripts/startup",
            # "src/bl_src/release/scripts/startup/bl_operators",
            # "src/bl_src/release/scripts/startup/bl_operators/bmesh",
            # "src/bl_src/release/scripts/startup/bl_ui",
            # "src/bl_src/release/scripts/startup/bl_app_templates_system",
            # "src/bl_src/release/scripts/startup/bl_app_templates_system/VFX",
            # "src/bl_src/release/scripts/startup/bl_app_templates_system/Video_Editing",
            # "src/bl_src/release/scripts/startup/bl_app_templates_system/Sculpting",
            # "src/bl_src/release/scripts/startup/bl_app_templates_system/2D_Animation",
            # "src/bl_src/release/scripts/modules",
            # "src/bl_src/release/scripts/modules/bl_ui_utils",
            # "src/bl_src/release/scripts/modules/gpu_extras",
            # "src/bl_src/release/scripts/modules/bpy",
            # "src/bl_src/release/scripts/modules/bpy/utils",
            # "src/bl_src/release/scripts/modules/bl_i18n_utils",
            # "src/bl_src/release/scripts/modules/bl_app_override",
            # "src/bl_src/release/scripts/modules/bl_keymap_utils",
            # "src/bl_src/release/scripts/modules/bl_previews_utils",
            # "src/bl_src/release/scripts/modules/bpy_extras",
            # "src/bl_src/release/scripts/modules/bpy_extras/wm_utils",
            # "src/bl_src/release/scripts/modules/console",
            # "src/bl_src/release/scripts/freestyle",
            # "src/bl_src/release/scripts/freestyle/styles",
            # "src/bl_src/release/scripts/freestyle/modules",
            # "src/bl_src/release/scripts/freestyle/modules/freestyle",
            # "src/bl_src/release/freedesktop",
            # "src/bl_src/release/freedesktop/icons",
            # "src/bl_src/release/freedesktop/icons/scalable",
            # "src/bl_src/release/freedesktop/icons/scalable/apps",
            # "src/bl_src/release/freedesktop/icons/symbolic",
            # "src/bl_src/release/freedesktop/icons/symbolic/apps",
            # "src/bl_src/release/freedesktop/snap",
            # "src/bl_src/release/darwin",
            # "src/bl_src/release/darwin/Blender.app",
            # "src/bl_src/release/darwin/Blender.app/Contents",
            # "src/bl_src/release/darwin/Blender.app/Contents/MacOS",
            # "src/bl_src/release/darwin/Blender.app/Contents/Resources",
            # "src/bl_src/release/darwin/buildbot",
            # "src/bl_src/release/datafiles",
            # "src/bl_src/release/datafiles/colormanagement",
            # "src/bl_src/release/datafiles/colormanagement/filmic",
            # "src/bl_src/release/datafiles/colormanagement/luts",
            # "src/bl_src/release/datafiles/locale",
            # "src/bl_src/release/datafiles/userdef",
            # "src/bl_src/release/datafiles/brushicons",
            # "src/bl_src/release/datafiles/studiolights",
            # "src/bl_src/release/datafiles/studiolights/studio",
            # "src/bl_src/release/datafiles/studiolights/world",
            # "src/bl_src/release/datafiles/studiolights/matcap",
            # "src/bl_src/release/datafiles/icons",
            # "src/bl_src/release/datafiles/blender_icons32",
            # "src/bl_src/release/datafiles/blender_icons16",
            # "src/bl_src/release/datafiles/fonts",
            # "src/bl_src/release/text",
            # "src/bl_src/release/windows",
            # "src/bl_src/release/windows/manifest",
            # "src/bl_src/release/windows/batch",
            # "src/bl_src/release/windows/icons",
            # "src/bl_src/release/windows/icons/cursors",
            # "src/bl_src/.github",
            # "src/bl_src/doc",
            # "src/bl_src/doc/python_api",
            # "src/bl_src/doc/python_api/rst",
            # "src/bl_src/doc/python_api/static",
            # "src/bl_src/doc/python_api/static/css",
            # "src/bl_src/doc/python_api/examples",
            # "src/bl_src/doc/license",
            # "src/bl_src/doc/guides",
            # "src/bl_src/doc/manpage",
            # "src/bl_src/doc/blender_file_format",
            # "src/bl_src/doc/doxygen",
            # "src/bl_src/intern",
            # "src/bl_src/intern/libmv",
            # "src/bl_src/intern/libmv/libmv",
            # "src/bl_src/intern/libmv/libmv/image",
            # "src/bl_src/intern/libmv/libmv/autotrack",
            # "src/bl_src/intern/libmv/libmv/numeric",
            # "src/bl_src/intern/libmv/libmv/simple_pipeline",
            # "src/bl_src/intern/libmv/libmv/tracking",
            # "src/bl_src/intern/libmv/libmv/multiview",
            # "src/bl_src/intern/libmv/libmv/logging",
            # "src/bl_src/intern/libmv/libmv/base",
            # "src/bl_src/intern/libmv/third_party",
            # "src/bl_src/intern/libmv/third_party/msinttypes",
            # "src/bl_src/intern/libmv/intern",
            # "src/bl_src/intern/glew-mx", TODO: check
            # "src/bl_src/intern/glew-mx/intern",
            # "src/bl_src/intern/cycles",
            # "src/bl_src/intern/cycles/app",
            # "src/bl_src/intern/cycles/test",
            # "src/bl_src/intern/cycles/cmake",
            # "src/bl_src/intern/cycles/util",
            # "src/bl_src/intern/cycles/graph",
            # "src/bl_src/intern/cycles/render",
            # "src/bl_src/intern/cycles/bvh",
            # "src/bl_src/intern/cycles/doc",
            # "src/bl_src/intern/cycles/doc/license",
            # "src/bl_src/intern/cycles/device",
            # "src/bl_src/intern/cycles/device/cuda",
            # "src/bl_src/intern/cycles/device/opencl",
            # "src/bl_src/intern/cycles/subd",
            # "src/bl_src/intern/cycles/blender",
            # "src/bl_src/intern/cycles/blender/addon",
            # "src/bl_src/intern/cycles/kernel",
            # "src/bl_src/intern/cycles/kernel/split",
            # "src/bl_src/intern/cycles/kernel/closure",
            # "src/bl_src/intern/cycles/kernel/kernels",
            # "src/bl_src/intern/cycles/kernel/kernels/cpu",
            # "src/bl_src/intern/cycles/kernel/kernels/cuda",
            # "src/bl_src/intern/cycles/kernel/kernels/optix",
            # "src/bl_src/intern/cycles/kernel/kernels/opencl",
            # "src/bl_src/intern/cycles/kernel/osl",
            # "src/bl_src/intern/cycles/kernel/bvh",
            # "src/bl_src/intern/cycles/kernel/svm",
            # "src/bl_src/intern/cycles/kernel/geom",
            # "src/bl_src/intern/cycles/kernel/shaders",
            # "src/bl_src/intern/cycles/kernel/filter",
            "src/bl_src/intern/guardedalloc",
            "src/bl_src/intern/guardedalloc/test",
            "src/bl_src/intern/guardedalloc/test/simpletest",
            "src/bl_src/intern/guardedalloc/cpp",
            "src/bl_src/intern/guardedalloc/intern",
            "src/bl_src/intern/ffmpeg",
            "src/bl_src/intern/opencolorio",
            "src/bl_src/intern/locale",
            "src/bl_src/intern/numaapi",
            "src/bl_src/intern/numaapi/include",
            "src/bl_src/intern/numaapi/source",
            "src/bl_src/intern/utfconv",
            "src/bl_src/intern/opensubdiv",
            "src/bl_src/intern/opensubdiv/internal",
            "src/bl_src/intern/opensubdiv/stub",
            "src/bl_src/intern/opensubdiv/shader",
            "src/bl_src/intern/mantaflow",
            "src/bl_src/intern/mantaflow/intern",
            "src/bl_src/intern/mantaflow/intern/strings",
            "src/bl_src/intern/mantaflow/extern",
            "src/bl_src/intern/clog",
            "src/bl_src/intern/libc_compat",
            "src/bl_src/intern/dualcon",
            "src/bl_src/intern/dualcon/intern",
            "src/bl_src/intern/memutil",
            "src/bl_src/intern/memutil/intern",
            "src/bl_src/intern/eigen",
            "src/bl_src/intern/eigen/intern",
            "src/bl_src/intern/atomic",
            "src/bl_src/intern/atomic/intern",
            "src/bl_src/intern/ghost",
            "src/bl_src/intern/ghost/test",
            "src/bl_src/intern/ghost/test/multitest",
            "src/bl_src/intern/ghost/test/gears",
            "src/bl_src/intern/ghost/intern",
            "src/bl_src/intern/quadriflow",
            "src/bl_src/intern/iksolver",
            "src/bl_src/intern/iksolver/intern",
            "src/bl_src/intern/iksolver/extern",
            "src/bl_src/intern/openvdb",
            "src/bl_src/intern/openvdb/intern",
            "src/bl_src/intern/string",
            "src/bl_src/intern/string/intern",
            "src/bl_src/intern/audaspace",
            "src/bl_src/intern/audaspace/intern",
            "src/bl_src/intern/mikktspace",
            "src/bl_src/intern/rigidbody",
            "src/bl_src/intern/itasc",
            "src/bl_src/intern/itasc/kdl",
            "src/bl_src/intern/itasc/kdl/utilities",
            "src/bl_src/extern",
            "src/bl_src/extern/wcwidth",
            "src/bl_src/extern/cuew",
            "src/bl_src/extern/cuew/include",
            "src/bl_src/extern/cuew/src",
            # "src/bl_src/extern/Eigen3",
            # "src/bl_src/extern/Eigen3/patches",
            # "src/bl_src/extern/Eigen3/Eigen",
            # "src/bl_src/extern/Eigen3/Eigen/src",
            # "src/bl_src/extern/Eigen3/Eigen/src/CholmodSupport",
            # "src/bl_src/extern/Eigen3/Eigen/src/misc",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/products",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/util",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/functors",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/SSE",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/CUDA",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/ZVector",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/Default",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/AVX512",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/AVX",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/NEON",
            # "src/bl_src/extern/Eigen3/Eigen/src/Core/arch/AltiVec",
            # "src/bl_src/extern/Eigen3/Eigen/src/SparseLU",
            # "src/bl_src/extern/Eigen3/Eigen/src/OrderingMethods",
            # "src/bl_src/extern/Eigen3/Eigen/src/plugins",
            # "src/bl_src/extern/Eigen3/Eigen/src/Householder",
            # "src/bl_src/extern/Eigen3/Eigen/src/PardisoSupport",
            # "src/bl_src/extern/Eigen3/Eigen/src/SparseCore",
            # "src/bl_src/extern/Eigen3/Eigen/src/Jacobi",
            # "src/bl_src/extern/Eigen3/Eigen/src/SPQRSupport",
            # "src/bl_src/extern/Eigen3/Eigen/src/QR",
            # "src/bl_src/extern/Eigen3/Eigen/src/Eigen2Support",
            # "src/bl_src/extern/Eigen3/Eigen/src/Eigen2Support/Geometry",
            # "src/bl_src/extern/Eigen3/Eigen/src/SparseQR",
            # "src/bl_src/extern/Eigen3/Eigen/src/SVD",
            # "src/bl_src/extern/Eigen3/Eigen/src/Cholesky",
            # "src/bl_src/extern/Eigen3/Eigen/src/UmfPackSupport",
            # "src/bl_src/extern/Eigen3/Eigen/src/IterativeLinearSolvers",
            # "src/bl_src/extern/Eigen3/Eigen/src/LU",
            # "src/bl_src/extern/Eigen3/Eigen/src/LU/arch",
            # "src/bl_src/extern/Eigen3/Eigen/src/Geometry",
            # "src/bl_src/extern/Eigen3/Eigen/src/Geometry/arch",
            # "src/bl_src/extern/Eigen3/Eigen/src/SuperLUSupport",
            # "src/bl_src/extern/Eigen3/Eigen/src/MetisSupport",
            # "src/bl_src/extern/Eigen3/Eigen/src/StlSupport",
            # "src/bl_src/extern/Eigen3/Eigen/src/SparseCholesky",
            # "src/bl_src/extern/Eigen3/Eigen/src/Eigenvalues",
            # "src/bl_src/extern/Eigen3/Eigen/src/PaStiXSupport",
            # "src/bl_src/extern/mantaflow",
            # "src/bl_src/extern/mantaflow/preprocessed",
            # "src/bl_src/extern/mantaflow/preprocessed/fileio",
            # "src/bl_src/extern/mantaflow/preprocessed/python",
            # "src/bl_src/extern/mantaflow/preprocessed/plugin",
            # "src/bl_src/extern/mantaflow/dependencies",
            # "src/bl_src/extern/mantaflow/dependencies/cnpy",
            # "src/bl_src/extern/mantaflow/helper",
            # "src/bl_src/extern/mantaflow/helper/pwrapper",
            # "src/bl_src/extern/mantaflow/helper/util",
            "src/bl_src/extern/xdnd",
            "src/bl_src/extern/glog",
            "src/bl_src/extern/glog/include",
            "src/bl_src/extern/glog/include/glog",
            "src/bl_src/extern/glog/src",
            "src/bl_src/extern/glog/src/windows",
            "src/bl_src/extern/glog/src/windows/glog",
            "src/bl_src/extern/glog/src/base",
            # "src/bl_src/extern/glew-es",
            # "src/bl_src/extern/glew-es/include",
            # "src/bl_src/extern/glew-es/include/GL",
            # "src/bl_src/extern/glew-es/src",
            # "src/bl_src/extern/draco",
            # "src/bl_src/extern/draco/dracoenc",
            # "src/bl_src/extern/draco/dracoenc/cmake",
            # "src/bl_src/extern/draco/dracoenc/cmake/toolchains",
            # "src/bl_src/extern/draco/dracoenc/src",
            # "src/bl_src/extern/draco/dracoenc/src/draco",
            # "src/bl_src/extern/draco/dracoenc/src/draco/mesh",
            # "src/bl_src/extern/draco/dracoenc/src/draco/tools",
            # "src/bl_src/extern/draco/dracoenc/src/draco/point_cloud",
            # "src/bl_src/extern/draco/dracoenc/src/draco/core",
            # "src/bl_src/extern/draco/dracoenc/src/draco/io",
            # "src/bl_src/extern/draco/dracoenc/src/draco/animation",
            # "src/bl_src/extern/draco/dracoenc/src/draco/attributes",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/mesh",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/mesh/traverser",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/point_cloud",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/point_cloud/algorithms",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/config",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/entropy",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/bit_coders",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/attributes",
            # "src/bl_src/extern/draco/dracoenc/src/draco/compression/attributes/prediction_schemes",
            # "src/bl_src/extern/draco/dracoenc/src/draco/metadata",
            # "src/bl_src/extern/draco/src",
            "src/bl_src/extern/gflags",
            "src/bl_src/extern/gflags/src",
            "src/bl_src/extern/gflags/src/gflags",
            "src/bl_src/extern/curve_fit_nd",
            "src/bl_src/extern/curve_fit_nd/intern",
            # "src/bl_src/extern/bullet2",
            # "src/bl_src/extern/bullet2/patches",
            # "src/bl_src/extern/bullet2/src",
            # "src/bl_src/extern/bullet2/src/BulletSoftBody",
            # "src/bl_src/extern/bullet2/src/BulletCollision",
            # "src/bl_src/extern/bullet2/src/BulletCollision/BroadphaseCollision",
            # "src/bl_src/extern/bullet2/src/BulletCollision/NarrowPhaseCollision",
            # "src/bl_src/extern/bullet2/src/BulletCollision/CollisionDispatch",
            # "src/bl_src/extern/bullet2/src/BulletCollision/Gimpact",
            # "src/bl_src/extern/bullet2/src/BulletCollision/CollisionShapes",
            # "src/bl_src/extern/bullet2/src/BulletDynamics",
            # "src/bl_src/extern/bullet2/src/BulletDynamics/Dynamics",
            # "src/bl_src/extern/bullet2/src/BulletDynamics/Vehicle",
            # "src/bl_src/extern/bullet2/src/BulletDynamics/Character",
            # "src/bl_src/extern/bullet2/src/BulletDynamics/Featherstone",
            # "src/bl_src/extern/bullet2/src/BulletDynamics/MLCPSolvers",
            # "src/bl_src/extern/bullet2/src/BulletDynamics/ConstraintSolver",
            # "src/bl_src/extern/bullet2/src/LinearMath",
            "src/bl_src/extern/rangetree",
            "src/bl_src/extern/rangetree/intern",
            "src/bl_src/extern/sdlew",
            "src/bl_src/extern/sdlew/include",
            "src/bl_src/extern/sdlew/include/SDL2",
            "src/bl_src/extern/sdlew/src",
            "src/bl_src/extern/gtest",
            "src/bl_src/extern/gtest/include",
            "src/bl_src/extern/gtest/include/gtest",
            "src/bl_src/extern/gtest/include/gtest/internal",
            "src/bl_src/extern/gtest/include/gtest/internal/custom",
            "src/bl_src/extern/gtest/src",
            # "src/bl_src/extern/quadriflow",
            # "src/bl_src/extern/quadriflow/patches",
            # "src/bl_src/extern/quadriflow/3rd",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/demo",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/tools",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/test",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/cmake",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/cmake/nsis",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/lemon",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/lemon/bits",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/lemon/concepts",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/contrib",
            # "src/bl_src/extern/quadriflow/3rd/lemon-1.3.1/scripts",
            # "src/bl_src/extern/quadriflow/3rd/pss",
            # "src/bl_src/extern/quadriflow/3rd/pss/pss",
            # "src/bl_src/extern/quadriflow/3rd/pcg32",
            # "src/bl_src/extern/quadriflow/3rd/pcg32/pcg32",
            # "src/bl_src/extern/quadriflow/src",
            # "src/bl_src/extern/ceres",
            # "src/bl_src/extern/ceres/config",
            # "src/bl_src/extern/ceres/config/ceres",
            # "src/bl_src/extern/ceres/config/ceres/internal",
            # "src/bl_src/extern/ceres/patches",
            # "src/bl_src/extern/ceres/include",
            # "src/bl_src/extern/ceres/include/ceres",
            # "src/bl_src/extern/ceres/include/ceres/internal",
            # "src/bl_src/extern/ceres/internal",
            # "src/bl_src/extern/ceres/internal/ceres",
            # "src/bl_src/extern/ceres/internal/ceres/generated",
            "src/bl_src/extern/binreloc",
            "src/bl_src/extern/binreloc/include",
            # "src/bl_src/extern/glew",
            # "src/bl_src/extern/glew/include",
            # "src/bl_src/extern/glew/include/GL",
            # "src/bl_src/extern/glew/src",
            "src/bl_src/extern/clew",
            "src/bl_src/extern/clew/include",
            "src/bl_src/extern/clew/src",
            # "src/bl_src/extern/audaspace",
            # "src/bl_src/extern/audaspace/config",
            # "src/bl_src/extern/audaspace/plugins",
            # "src/bl_src/extern/audaspace/plugins/ffmpeg",
            # "src/bl_src/extern/audaspace/plugins/openal",
            # "src/bl_src/extern/audaspace/plugins/sdl",
            # "src/bl_src/extern/audaspace/plugins/jack",
            # "src/bl_src/extern/audaspace/plugins/libsndfile",
            # "src/bl_src/extern/audaspace/include",
            # "src/bl_src/extern/audaspace/include/util",
            # "src/bl_src/extern/audaspace/include/file",
            # "src/bl_src/extern/audaspace/include/fx",
            # "src/bl_src/extern/audaspace/include/plugin",
            # "src/bl_src/extern/audaspace/include/respec",
            # "src/bl_src/extern/audaspace/include/generator",
            # "src/bl_src/extern/audaspace/include/sequence",
            # "src/bl_src/extern/audaspace/include/devices",
            # "src/bl_src/extern/audaspace/bindings",
            # "src/bl_src/extern/audaspace/bindings/python",
            # "src/bl_src/extern/audaspace/bindings/python/examples",
            # "src/bl_src/extern/audaspace/bindings/doc",
            # "src/bl_src/extern/audaspace/bindings/C",
            # "src/bl_src/extern/audaspace/src",
            # "src/bl_src/extern/audaspace/src/util",
            # "src/bl_src/extern/audaspace/src/file",
            # "src/bl_src/extern/audaspace/src/fx",
            # "src/bl_src/extern/audaspace/src/plugin",
            # "src/bl_src/extern/audaspace/src/respec",
            # "src/bl_src/extern/audaspace/src/generator",
            # "src/bl_src/extern/audaspace/src/sequence",
            # "src/bl_src/extern/audaspace/src/devices",
            # "src/bl_src/extern/lzma",
            # "src/bl_src/extern/lzo",
            # "src/bl_src/extern/lzo/minilzo",
            # "src/bl_src/extern/gmock",
            # "src/bl_src/extern/gmock/include",
            # "src/bl_src/extern/gmock/include/gmock",
            # "src/bl_src/extern/gmock/include/gmock/internal",
            # "src/bl_src/extern/gmock/include/gmock/internal/custom",
            # "src/bl_src/extern/gmock/src",
            ],
        language="c++",
        extra_compile_args=extra_compile_args,
        extra_link_args=extra_link_args,
        libraries=['opengl32'] if platform.system() == 'Windows' else [],
        #extra_objects=["src/libglew.a"],
        #library_dirs=['src']
    )]
    ),
    libraries=[glew],
    requires=['Cython'])

